apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dark8-agent.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints","configmaps","secrets"]
    verbs: ["get","list","watch","create","update","patch"]
