{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
type: Opaque
stringData:
  # put your secrets here
  OLLAMA_HOST: ""
  OLLAMA_PORT: ""
{{- end }}
