{{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dark8-agent.serviceAccountName" . }}
  labels:
    app: {{ include "dark8-agent.name" . }}
{{- end }}
