apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dark8-studio.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints"]
    verbs: ["get","list","watch"]
