apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dark8-studio.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "dark8-studio.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "dark8-studio.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
