apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dark8.fullname" . }}-config
data:
{{- if .Values.config }}
{{ toYaml .Values.config | indent 2 }}
{{- else }}
  # example: API_KEY: "changeme"
{{- end }}
