{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dark8.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | default "" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dark8.fullname" . | default "dark8-core" }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: {{ toYaml .Values.ingress.tls.hosts | nindent 6 }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}
