apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dark8.fullname" . }}-secret
type: Opaque
stringData:
{{- if .Values.secrets }}
{{ toYaml .Values.secrets | indent 2 }}
{{- else }}
  # EXAMPLE_SECRET: "changeme"
{{- end }}
