apiVersion: v1
kind: Service
metadata:
  name: {{ include "dark8.fullname" . | default "dark8-core" }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "dark8.name" . | default "dark8-core" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
