apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "dark8.fullname" .) }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
